region: "us-east-1"
env: "dev"
bucket_name: "default-ansible-bucket"
action: "create"
common_tags:
  Owner: ansible
  Project: aws
  Environment: "{{ env }}"

ansible_user: ec2-user
ansible_password: DevOps321