- name: "Create aws s3 bucket"
  amazon.aws.s3_bucket:
    name: "{{ bucket_name }}-{{ env }}"
    region: "{{ region }}"
    state: present
    versioning: true
    encryption: "AES256"
    acl: "private"
    object_lock_configuration:
      object_lock_enabled: "Enabled"
      object_lock_default_retention:
                  mode: "GOVERNANCE"
                  days: 30
    object_ownership_controls:
      object_ownership: "BucketOwnerPreferred"
    public_access:
      block_public_acls: true
      block_public_policy: true
      ignore_public_acls: true
      restrict_public_buckets: true
    policy: "{{ lookup('template','policy.json') }}"
    tags: "{{ common_tags }}"
  when:
    - action == "create"
  register: s3_output

- name: "Display the message"
  ansible.builtin.debug:
    msg: "Bucket {{ bucket_name }}-{{ env }} created successfully"
  when: s3_output.changed